### ISSUE TITLE
Bug cuando cambias de empresa

### ISSUE THREAD

**Issue by NoelBroda** [ciberlunes/ciberlunes.github.io#5]
Pasos par reproducir:

* Filtrar por `cafetera`
* Seleccionar otra empresa.

El filtro no esta aplicado

**Comment by ciberlunes** [comment]
Si, lo había visto, pero esperé que nadie se de cuenta... Ahora lo reviso y te digo (debe ser una boludez).

**Comment by lisandro52** [comment]
Listo esto! Limpiá la caché por si acaso.

**Comment by ciberlunes** [comment]
Listo esto! Limpia caché por si acaso
